#!/usr/bin/env bash

dotlink() {
    local src="$1"
    local dest="$2"
    local path
    path="$dest/$(basename "$src")"

    [[ ! -e "$src" ]] && return 1
    if [[ -e "$path" && ! -L "$path" ]]; then
        printf >&2 -- 'Moving non-linked %s to Trash.\n' "$path"
        mv -v -- "$path" "$HOME/.Trash"
    fi

    if [[ -d "$src" ]]; then
        ln -sFv -- "$src" "$dest"
    elif [[ -f "$src" ]]; then
        ln -sfv -- "$src" "$dest"
    fi
}

bootstrap() {
    local iCloud="$HOME/Library/Mobile Documents/com~apple~CloudDocs"
    local -a targets=('.vim' '.vimrc' '.xvimrc' '.zshrc' '.zshenv' '.ipython'
    '.bin' '.tigrc' '.git_template' '.gitignore' '.gitconfig' '.tmux.conf'
    "$iCloud/.weechat")
    local -a vim_targets=("$iCloud/Vim/pack" "$iCloud/Vim/spell")
    local -a config_targets=('mpv')

    local target
    for target in "${targets[@]}";        do dotlink "$(realpath "$target")" "$HOME";         done
    for target in "${vim_targets[@]}";    do dotlink "$(realpath "$target")" "$HOME/.vim";    done
    for target in "${config_targets[@]}"; do dotlink "$(realpath "$target")" "$HOME/.config"; done

    mkdir -p "$HOME/.vim/backup/undo"
}

bootstrap
