#!/usr/bin/env bash

function header() {
    echo -e "`tput bold`$1`tput sgr0`"
}

function link_file {
    header "Linking $1..."
    local prev=`pwd`
    cd $HOME && /bin/ln -sfv $1 && cd $prev
}

function link_folder {
    header "Linking $1..."
    local prev=`pwd`
    cd $HOME && /bin/ln -sFv $1 && cd $prev
}

function install_homebrew {
    # Install homebrew if needed
    echo "${bold}Checking if Homebrew is installed...${norm}"
    if [ ! -x /usr/local/bin/brew ]; then
        echo -e "${bold}\nHomebrew not installed. Installing it now...${norm}"
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    # Install homebrew apps
    header "\nInstalling homebrew apps..."
    brew install ag aspell chruby clang-format ctags colordiff diff-so-fancy fasd \
        python3 ruby-install reattach-to-user-namespace tig
    brew install git --without-completions --with-pcre --with-brewed-curl --with-brewed-openssl
    brew install vim --disable-nls --without-perl --without-ruby --override-system-vi
    brew install weechat --with-aspell --with-lua --with-perl --with-python --with-ruby
    brew install pinentry-mac gpg gpg-agent
    header "\nDone installing homebrew apps!"
    pip3 install ipython flake8
}

function setup_vim {
    link_folder ~/dotfiles/.vim
    link_file ~/dotfiles/.vimrc
    link_file ~/dotfiles/.xvimrc

    header "Creating vim backup folders..."
    mkdir -p ~/.vim/backup/undo
    if [ ! -d ~/.vim/bundle/ ]; then
        mkdir ~/.vim/bundle
    fi

    . ~/Library/Mobile\ Documents/com~apple~CloudDocs/Vim/vimutil/install_bundles
}

function setup_shell_tools {
    cd $HOME

    link_folder ~/dotfiles/.zsh
    link_file ~/dotfiles/.zshrc
    link_file ~/dotfiles/.zshenv

    link_folder ~/Library/Mobile\ Documents/com~apple~CloudDocs/.gnupg
    link_folder ~/dotfiles/.ipython
    link_folder ~/dotfiles/.bin
    link_file ~/dotfiles/.agignore
}

function setup_osx_defaults {
    header "\nSetting up OS X defaults..."
    [ ! -d $HOME/.cache ] && mkdir $HOME/.cache
    defaults write com.apple.Finder QLEnableTextSelection -bool true
    defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
    defaults write NSGlobalDomain KeyRepeat -int 0
    defaults write com.apple.dock expose-animation-duration -float 0.15
}

function setup_git {
    link_file ~/dotfiles/.tigrc
    link_folder ~/dotfiles/.git_template
}

header "==> Do you wish to proceed with bootstrapping?"
select yn in "Yes" "No"; do
case $yn in
    Yes ) echo "Okay, proceeding..." && break;;
    No) echo "Okay, stopping..." && exit;;
esac; done

# OS X specific config
if [ `uname` == "Darwin" ]; then
    install_homebrew
    setup_vim
    setup_shell_tools
    setup_git
    setup_osx_defaults
    header "\nDone!"
fi
