#!/usr/bin/env zsh

dotlink() {
    local src="$1"
    local dest="$2"
    local path
    path="$dest/$src:t"

    [[ ! -e "$src" ]] && return 1
    if [[ -e "$path" && ! -L "$path" ]]; then
        printf >&2 -- 'Moving non-linked %s to Trash.\n' "$path"
        /bin/mv -v -- "$path" "$HOME/.Trash"
    fi

    if [[ -d "$src" ]]; then
        /bin/ln -sFv -- "$src" "$dest"
    elif [[ -f "$src" ]]; then
        /bin/ln -sfv -- "$src" "$dest"
    fi
}

bootstrap() {
    local iCloud="$HOME/Library/Mobile Documents/com~apple~CloudDocs"
    local -a targets=('.vim' '.vimrc' '.xvimrc' '.zshrc' '.zshenv' '.ipython'
    '.bin' '.tigrc' '.ctags' '.git_template' '.gitignore' '.gitconfig'
    '.gitattributes' '.tmux.conf' ".mutt" "$iCloud/.weechat")
    local -a vim_targets=("$iCloud/Vim/pack" "$iCloud/Vim/spell")
    local -a config_targets=('mpv')

    local target
    for target in "${targets[@]}";        do dotlink "$target:P" "$HOME";         done
    for target in "${vim_targets[@]}";    do dotlink "$target:P" "$HOME/.vim";    done
    for target in "${config_targets[@]}"; do dotlink "$target:P" "$HOME/.config"; done

    mkdir -p "$HOME/.vim/backup/undo"
}

bootstrap
