#!/usr/bin/env zsh

checksum() {
    if [[ -z "$1" ]]; then
        printf >&2 'Usage:\t%s <remote_object>\n' "$0"
        return 1
    fi
    curl -sL "$1" | shasum -a 512 | awk '{printf substr($1, 1, 65)}' | pbcopy
}
checksum "$1"
